--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CortexPE/DiscordWebhookAPI
branches:
  - master
projects:
  DiscordWebhookAPI:
    model: virion
    type: library
    lint:
      phpstan: false
...
